name: assistant
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  provider: ^6.1.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  shared_preferences: ^2.2.2
  syncfusion_flutter_gauges: ^23.2.7
  tuple: ^2.0.2
  intl: ^0.18.1
  expandable_bottom_sheet: ^1.1.1+1
  weather_animation: ^1.0.1
  flutter_bloc: ^8.1.3
  flutter_animated_icons: ^1.0.1
  lottie: ^1.4.3
  flutter_rating_bar: ^4.0.1
  dropdown_search: ^5.0.6
  wheel_picker: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true